-- Add missing columns that the frontend expects
ALTER TABLE actions ADD COLUMN IF NOT EXISTS frequency TEXT;
ALTER TABLE actions ADD COLUMN IF NOT EXISTS duration INTEGER;
ALTER TABLE actions ADD COLUMN IF NOT EXISTS days_per_week INTEGER;
ALTER TABLE actions ADD COLUMN IF NOT EXISTS time_of_day TIME;
ALTER TABLE actions ADD COLUMN IF NOT EXISTS category TEXT;

-- Also ensure RLS is disabled
ALTER TABLE goals DISABLE ROW LEVEL SECURITY;
ALTER TABLE actions DISABLE ROW LEVEL SECURITY;
ALTER TABLE posts DISABLE ROW LEVEL SECURITY;
ALTER TABLE reactions DISABLE ROW LEVEL SECURITY;
ALTER TABLE profiles DISABLE ROW LEVEL SECURITY;
ALTER TABLE follows DISABLE ROW LEVEL SECURITY;
ALTER TABLE streaks DISABLE ROW LEVEL SECURITY;

SELECT 'Added missing columns and disabled RLS!' as message;