-- TEMPORARILY DISABLE RLS FOR TESTING
-- Run this in Supabase SQL Editor
-- WARNING: This removes all security - only use for testing!

-- Disable RLS on all tables
ALTER TABLE goals DISABLE ROW LEVEL SECURITY;
ALTER TABLE actions DISABLE ROW LEVEL SECURITY;
ALTER TABLE posts DISABLE ROW LEVEL SECURITY;
ALTER TABLE reactions DISABLE ROW LEVEL SECURITY;
ALTER TABLE profiles DISABLE ROW LEVEL SECURITY;
ALTER TABLE follows DISABLE ROW LEVEL SECURITY;
ALTER TABLE streaks DISABLE ROW LEVEL SECURITY;

SELECT 'RLS DISABLED - All tables are now publicly accessible for testing!' as message;

-- To re-enable RLS later, run:
-- ALTER TABLE goals ENABLE ROW LEVEL SECURITY;
-- ALTER TABLE actions ENABLE ROW LEVEL SECURITY;
-- ALTER TABLE posts ENABLE ROW LEVEL SECURITY;
-- ALTER TABLE reactions ENABLE ROW LEVEL SECURITY;
-- ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;
-- ALTER TABLE follows ENABLE ROW LEVEL SECURITY;
-- ALTER TABLE streaks ENABLE ROW LEVEL SECURITY;